#!/usr/local/bin/perl -w
# Copyright (C) 2000, Free Software Foundation FSF.

use lib '..';
use PPresenter;
use strict;

my $show = new PPresenter
( -name     => 'Decorations'
);

$show->select( decoration => 'lines1' )
     ->change( -pageLogo  => 'gpp_medium.gif'
             );
 
$show->change( template   => 'ALL'
             , -showTemplateOutlines => 1
             );

$show->addSlide
( -title => 'titel'
, -footer => 'footer'
);

$show->run;
